name: Update Space Shooter Game

on:
  schedule:
    - cron: "0 */12 * * *"  # run automatically every 12 hours
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write

jobs:
  update-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: czl9707/gh-space-shooter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: 'space-shooter.webp'
          strategy: 'random'
